Repository subspace/auto-mobile, pull requests merged in 2024-01, with the labels that each got.

#18 Fix build issue during past PR conflicts
  packages/sdk/src/library/utils.ts
  packages/sdk/src/library/wallet.ts
  packages/sdk/src/shamir-secret-sharing/csprng.ts
Labels: bug, enhancement

#19 Improved function: retrieve Auto Wallet
  apps/auto-app/app/utils/genAutoWallet.ts
  packages/sdk/src/examples/getAutoWallet.ts
  packages/sdk/src/library/wallet.ts
Labels: enhancement

#20 Renaming contract function to `register`
  packages/sdk/abi/DidRegistry.json
  packages/sdk/src/library/wallet.ts
Labels: enhancement

#25 impr: add transactions screens
  apps/auto-app/App.tsx
  apps/auto-app/app.config.ts
  apps/auto-app/app.json
  apps/auto-app/app/components/Contatcs/ContactItem.tsx
  apps/auto-app/app/components/Payment/PaymentPad.tsx
  apps/auto-app/app/components/ProgressBar/ProgressBar.tsx
  apps/auto-app/app/components/Toggle.tsx
  apps/auto-app/app/components/Transaction/ContactDetails.tsx
  apps/auto-app/app/components/Transaction/CurrencySelect.tsx
  apps/auto-app/app/components/Transaction/TransactionHeader.tsx
  apps/auto-app/app/components/WalletTabBar/WalletTabBar.tsx
  apps/auto-app/app/components/WalletTabBar/WalletTabBar.utils.tsx
  apps/auto-app/app/components/WalletTabBar/index.ts
  apps/auto-app/app/models/RootStore.ts
  apps/auto-app/app/models/Transaction.ts
  apps/auto-app/app/navigators/AppNavigator.tsx
  apps/auto-app/app/navigators/WalletNavigator.tsx
  apps/auto-app/app/navigators/WalletWelcomeNavigator.tsx
  apps/auto-app/app/screens/LastDetailsScreen.tsx
  apps/auto-app/app/screens/RecoveryPhraseScreen.tsx
  apps/auto-app/app/screens/SendPaymentScreen.tsx
  apps/auto-app/app/screens/SendingPaymentScreen.tsx
  apps/auto-app/app/screens/SetupAutoIdScreen.tsx
  apps/auto-app/app/screens/Wallet/PaymentDoneScreen.tsx
  apps/auto-app/app/screens/Wallet/SearchFriendScreen.tsx
  apps/auto-app/app/screens/WalletWelcomeScreen.tsx
  apps/auto-app/app/screens/index.ts
  apps/auto-app/app/utils/contact.ts
  apps/auto-app/app/utils/useAsyncIncrementalNumber.ts
  apps/auto-app/data/contacts.ts
  apps/auto-app/index.js
  apps/auto-app/metro.config.js
  apps/auto-app/package.json
  pnpm-lock.yaml
Labels: enhancement

#26 Modify Backend
  README.md
  apps/auto-app-example/package.json
  apps/auto-app-example/utils.ts
  apps/auto-app/app/components/Wallet/WalletHeader.tsx
  apps/auto-app/app/utils/genAutoWallet.ts
  apps/auto-app/package.json
  packages/backend/.eslintrc.json
  packages/backend/.gitignore
  packages/backend/.nvmrc
  packages/backend/.watchmanconfig
  packages/backend/abi/DidRegistry.json
  packages/backend/babel.config.js
  packages/backend/global.d.ts
  packages/backend/lefthook.yml
  packages/backend/package.json
  packages/backend/src/examples/README.md
  packages/backend/src/examples/e2eSeedRecovery.ts
  packages/backend/src/examples/genAutoWallet.ts
  packages/backend/src/examples/getAutoId.ts
  packages/backend/src/examples/getAutoWallet.ts
  packages/backend/src/examples/getEvmAddrs.ts
  packages/backend/src/examples/isAutoIdVerified.ts
  packages/backend/src/examples/payOnNova.ts
  packages/backend/src/examples/sss.ts
  packages/backend/src/index.tsx
  packages/backend/src/library/constants.ts
  packages/backend/src/library/did.ts
  packages/backend/src/library/pay.ts
  packages/backend/src/library/recovery.ts
  packages/backend/src/library/utils.ts
  packages/backend/src/library/wallet.ts
  packages/backend/src/shamir-secret-sharing/csprng.ts
  packages/backend/src/shamir-secret-sharing/index.ts
  packages/backend/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement

#32 doc: add readme file
  README.md
  assets/GettingStartedXcodeCommandLineTools.png
Labels: documentation
